# Generated by Django 2.2.1 on 2019-05-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='pages',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='products',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='series',
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventories.Genre'),
        ),
        migrations.AlterUniqueTogether(
            name='detail',
            unique_together={('product', 'cover_type', 'language', 'publisher', 'publish_date')},
        ),
        migrations.DeleteModel(
            name='ProductSeries',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
